language: python
python:
  - "2.7"
  - "3.5"

# command to install dependencies
install: 
  - pip install -q -U pip setuptools tox coveralls

# command to run tests
script: 
  tox

after_success:
  coveralls