language: python
python:
  - "3.5"

# command to install dependencies
install: 
  - pip install -q -U pip setuptools tox coverage

# command to run tests
script: 
  tox

after_success:
  coveralls
  # codecov 
  # - bash <(curl -s https://codecov.io/bash)
